/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	kubexposev1 "kubexpose/pkg/apis/kubexpose/v1"
	versioned "kubexpose/pkg/client/clientset/versioned"
	internalinterfaces "kubexpose/pkg/client/informers/externalversions/internalinterfaces"
	v1 "kubexpose/pkg/client/listers/kubexpose/v1"
	time "time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// KubexposeInformer provides access to a shared informer and lister for
// Kubexposes.
type KubexposeInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.KubexposeLister
}

type kubexposeInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewKubexposeInformer constructs a new informer for Kubexpose type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewKubexposeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredKubexposeInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredKubexposeInformer constructs a new informer for Kubexpose type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredKubexposeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AbhirockzzV1().Kubexposes(namespace).List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AbhirockzzV1().Kubexposes(namespace).Watch(options)
			},
		},
		&kubexposev1.Kubexpose{},
		resyncPeriod,
		indexers,
	)
}

func (f *kubexposeInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredKubexposeInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *kubexposeInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&kubexposev1.Kubexpose{}, f.defaultInformer)
}

func (f *kubexposeInformer) Lister() v1.KubexposeLister {
	return v1.NewKubexposeLister(f.Informer().GetIndexer())
}
