/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "kubexpose/pkg/apis/kubexpose/v1"
	scheme "kubexpose/pkg/client/clientset/versioned/scheme"
	"time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// KubexposesGetter has a method to return a KubexposeInterface.
// A group's client should implement this interface.
type KubexposesGetter interface {
	Kubexposes(namespace string) KubexposeInterface
}

// KubexposeInterface has methods to work with Kubexpose resources.
type KubexposeInterface interface {
	Create(*v1.Kubexpose) (*v1.Kubexpose, error)
	Update(*v1.Kubexpose) (*v1.Kubexpose, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.Kubexpose, error)
	List(opts metav1.ListOptions) (*v1.KubexposeList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Kubexpose, err error)
	KubexposeExpansion
}

// kubexposes implements KubexposeInterface
type kubexposes struct {
	client rest.Interface
	ns     string
}

// newKubexposes returns a Kubexposes
func newKubexposes(c *AbhirockzzV1Client, namespace string) *kubexposes {
	return &kubexposes{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the kubexpose, and returns the corresponding kubexpose object, and an error if there is any.
func (c *kubexposes) Get(name string, options metav1.GetOptions) (result *v1.Kubexpose, err error) {
	result = &v1.Kubexpose{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("kubexposes").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Kubexposes that match those selectors.
func (c *kubexposes) List(opts metav1.ListOptions) (result *v1.KubexposeList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.KubexposeList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("kubexposes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested kubexposes.
func (c *kubexposes) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("kubexposes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a kubexpose and creates it.  Returns the server's representation of the kubexpose, and an error, if there is any.
func (c *kubexposes) Create(kubexpose *v1.Kubexpose) (result *v1.Kubexpose, err error) {
	result = &v1.Kubexpose{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("kubexposes").
		Body(kubexpose).
		Do().
		Into(result)
	return
}

// Update takes the representation of a kubexpose and updates it. Returns the server's representation of the kubexpose, and an error, if there is any.
func (c *kubexposes) Update(kubexpose *v1.Kubexpose) (result *v1.Kubexpose, err error) {
	result = &v1.Kubexpose{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("kubexposes").
		Name(kubexpose.Name).
		Body(kubexpose).
		Do().
		Into(result)
	return
}

// Delete takes name of the kubexpose and deletes it. Returns an error if one occurs.
func (c *kubexposes) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("kubexposes").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *kubexposes) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("kubexposes").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched kubexpose.
func (c *kubexposes) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Kubexpose, err error) {
	result = &v1.Kubexpose{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("kubexposes").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
